/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./CryptoPredictor.types";
import * as _1 from "./CryptoPredictor.client";
import * as _2 from "./CryptoPredictor.message-composer";
export namespace contracts {
  export const CryptoPredictor = {
    ..._0,
    ..._1,
    ..._2
  };
}